@startuml

abstract class Person {
    -name: String
    -alter: int
    greetings()
}

class Teacher {
    -name: String
    -alter: int
    Teacher(name, alter)
    greetings()
}

class Student {
    -name: String
    -alter: int
    Student(name, alter)
    greetings()
}

Person <|-- Teacher
Person <|-- Student
@enduml

